language: ruby

rvm:
  - 2.2.4

before_install: sudo apt-get update && sudo apt-get install vim-gtk

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

notifications:
 email:
   on_success: change
   on_failure: always
